# Generated by Django 5.1.2 on 2024-10-29 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District Of Columbia', 'District Of Columbia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=100)),
                ('city', models.CharField(choices=[('New York City', 'New York City'), ('Los Angeles', 'Los Angeles'), ('Chicago', 'Chicago'), ('Houston', 'Houston'), ('Phoenix', 'Phoenix'), ('Philadelphia', 'Philadelphia'), ('San Antonio', 'San Antonio'), ('San Diego', 'San Diego'), ('Dallas', 'Dallas'), ('San Jose', 'San Jose'), ('Atlanta', 'Atlanta'), ('Miami', 'Miami'), ('Boston', 'Boston'), ('Detroit', 'Detroit'), ('Seattle', 'Seattle'), ('Denver', 'Denver'), ('Washington D.C.', 'Washington D.C.'), ('Las Vegas', 'Las Vegas'), ('Portland', 'Portland'), ('Oklahoma City', 'Oklahoma City')], max_length=100)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Brown', 'Brown'), ('Gold', 'Gold'), ('Pink', 'Pink'), ('Purple', 'Purple')], max_length=100)),
                ('model', models.CharField(choices=[('Ferrari 480 GTB', 'Ferrari 480 GTB'), ('Ferrari F8 Tributo', 'Ferrari F8 Tributo'), ('Tesla Model 3', 'Tesla Model 3'), ('Tesla Model Y Performance', 'Tesla Model Y Performance'), ('Ford Mustang', 'Ford Mustang'), ('Ford Ranger Raptor', 'Ford Ranger Raptor'), ('Toyota Camry', 'Toyota Camry'), ('Toyota Prius', 'Toyota Prius'), ('Benz CLA-Class', 'Benz CLA-Class'), ('Benz GLA-Class', 'Benz GLA-Class'), ('BMW 3 Series', 'BMW 3 Series'), ('BMW X5', 'BMW X5'), ('Honda Civic', 'Honda Civic'), ('Nissan Altima', 'Nissan Altima'), ('Volkswagen Scirocco', 'Volkswagen Scirocco'), ('Audi A4', 'Audi A4'), ('Maserati Ghibli', 'Maserati Ghibli'), ('Lamborghini Huracán', 'Lamborghini Huracán')], max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='year')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('First Hand', 'First Hand'), ('Test Drive', 'Test Drive'), ('Refurbished', 'Refurbished'), ('Certified Pre-Owned', 'Certified Pre-Owned')], max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('features', models.CharField(max_length=255)),
                ('body_style', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Pickup Truck', 'Pickup Truck'), ('Van', 'Van')], max_length=100)),
                ('engine', models.CharField(choices=[('Internal Combustion Engine', 'Internal Combustion Engine'), ('Electric Vehicle', 'Electric Vehicle'), ('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Plug-in Hybrid Electric Vehicle', 'Plug-in Hybrid Electric Vehicle'), ('Fuel Cell Electric Vehicle', 'Fuel Cell Electric Vehicle')], max_length=100)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Continuously Variable Transmission', 'Continuously Variable Transmission'), ('Dual-Clutch Transmission', 'Dual-Clutch Transmission'), ('Semi-Automatic', 'Semi-Automatic')], max_length=100)),
                ('interior', models.CharField(choices=[('Cloth', 'Cloth'), ('Leather', 'Leather'), ('Vinyl', 'Vinyl'), ('Suede', 'Suede'), ('Mixed Materials', 'Mixed Materials')], max_length=100)),
                ('miles', models.IntegerField()),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('passengers', models.IntegerField()),
                ('vin_no', models.CharField(max_length=50)),
                ('milage', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Compressed Natural Gas', 'Compressed Natural Gas'), ('E85 Ethanol', 'E85 Ethanol'), ('Biodiesel', 'Biodiesel')], max_length=50)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Car_at_top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('car_image_at_top', models.ImageField(upload_to='photo/top_pge/%Y/%m/%d')),
            ],
        ),
    ]
