# Generated by Django 5.1.2 on 2024-10-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='for_rented',
            field=models.BooleanField(default=False),
        ),
    ]
